name: Build and deploy to gh-pages

on:
  push:
    branches: [ main ]        # or whatever your source branch is

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm ci

      - name: Build with GitHub-Pages path
        env:
          # This tells CRA to prefix *every* asset URL with /headsgone
          PUBLIC_URL: '/headsgone'
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          # optional: set the cname if you’re using a custom domain here:
          # cname: headsg.one
